// seed/data.js
//
// Realistic seed data: a small citation graph built from well-known,
// publicly documented machine learning papers. Titles, years, venues and
// authorship are factual/bibliographic; abstracts below are short original
// summaries written for this demo, not copied from the papers themselves.

const venues = [
  { id: "v-neurips", name: "NeurIPS", kind: "conference" },
  { id: "v-icml", name: "ICML", kind: "conference" },
  { id: "v-iclr", name: "ICLR", kind: "conference" },
  { id: "v-cvpr", name: "CVPR", kind: "conference" },
  { id: "v-acl", name: "ACL", kind: "conference" },
  { id: "v-naacl", name: "NAACL", kind: "conference" },
  { id: "v-jmlr", name: "JMLR", kind: "journal" },
  { id: "v-nature", name: "Nature", kind: "journal" },
  { id: "v-neural-comp", name: "Neural Computation", kind: "journal" },
  { id: "v-arxiv", name: "arXiv preprint", kind: "preprint" },
];

const topics = [
  { id: "t-dl", name: "Deep Learning" },
  { id: "t-nlp", name: "Natural Language Processing" },
  { id: "t-cv", name: "Computer Vision" },
  { id: "t-rl", name: "Reinforcement Learning" },
  { id: "t-opt", name: "Optimization" },
  { id: "t-gen", name: "Generative Models" },
  { id: "t-attn", name: "Attention Mechanisms" },
  { id: "t-arch", name: "Neural Architecture" },
  { id: "t-repr", name: "Representation Learning" },
  { id: "t-compress", name: "Model Compression" },
];

const authors = [
  { id: "a-hochreiter", name: "Sepp Hochreiter", affiliation: "TU Linz", hIndex: 96 },
  { id: "a-schmidhuber", name: "Jürgen Schmidhuber", affiliation: "IDSIA", hIndex: 118 },
  { id: "a-mikolov", name: "Tomas Mikolov", affiliation: "Google", hIndex: 60 },
  { id: "a-sutskever", name: "Ilya Sutskever", affiliation: "OpenAI", hIndex: 110 },
  { id: "a-krizhevsky", name: "Alex Krizhevsky", affiliation: "University of Toronto", hIndex: 55 },
  { id: "a-hinton", name: "Geoffrey Hinton", affiliation: "University of Toronto", hIndex: 190 },
  { id: "a-srivastava", name: "Nitish Srivastava", affiliation: "University of Toronto", hIndex: 30 },
  { id: "a-salakhutdinov", name: "Ruslan Salakhutdinov", affiliation: "Carnegie Mellon University", hIndex: 100 },
  { id: "a-simonyan", name: "Karen Simonyan", affiliation: "DeepMind", hIndex: 60 },
  { id: "a-zisserman", name: "Andrew Zisserman", affiliation: "University of Oxford", hIndex: 150 },
  { id: "a-goodfellow", name: "Ian Goodfellow", affiliation: "Google Brain", hIndex: 100 },
  { id: "a-bengio", name: "Yoshua Bengio", affiliation: "Université de Montréal", hIndex: 200 },
  { id: "a-vinyals", name: "Oriol Vinyals", affiliation: "DeepMind", hIndex: 100 },
  { id: "a-le", name: "Quoc V. Le", affiliation: "Google Brain", hIndex: 110 },
  { id: "a-bahdanau", name: "Dzmitry Bahdanau", affiliation: "Université de Montréal", hIndex: 40 },
  { id: "a-cho", name: "Kyunghyun Cho", affiliation: "New York University", hIndex: 90 },
  { id: "a-kingma", name: "Diederik P. Kingma", affiliation: "OpenAI", hIndex: 70 },
  { id: "a-ba", name: "Jimmy Ba", affiliation: "University of Toronto", hIndex: 55 },
  { id: "a-ioffe", name: "Sergey Ioffe", affiliation: "Google", hIndex: 40 },
  { id: "a-szegedy", name: "Christian Szegedy", affiliation: "Google", hIndex: 90 },
  { id: "a-he", name: "Kaiming He", affiliation: "FAIR", hIndex: 130 },
  { id: "a-sun", name: "Jian Sun", affiliation: "Megvii", hIndex: 100 },
  { id: "a-mnih", name: "Volodymyr Mnih", affiliation: "DeepMind", hIndex: 55 },
  { id: "a-kavukcuoglu", name: "Koray Kavukcuoglu", affiliation: "DeepMind", hIndex: 70 },
  { id: "a-silver", name: "David Silver", affiliation: "DeepMind", hIndex: 100 },
  { id: "a-hassabis", name: "Demis Hassabis", affiliation: "DeepMind", hIndex: 60 },
  { id: "a-vaswani", name: "Ashish Vaswani", affiliation: "Google Brain", hIndex: 45 },
  { id: "a-shazeer", name: "Noam Shazeer", affiliation: "Google Brain", hIndex: 55 },
  { id: "a-jones", name: "Llion Jones", affiliation: "Google Brain", hIndex: 25 },
  { id: "a-devlin", name: "Jacob Devlin", affiliation: "Google", hIndex: 40 },
  { id: "a-radford", name: "Alec Radford", affiliation: "OpenAI", hIndex: 55 },
  { id: "a-peters", name: "Matthew Peters", affiliation: "Allen Institute for AI", hIndex: 35 },
  { id: "a-dai", name: "Zihang Dai", affiliation: "Carnegie Mellon University", hIndex: 30 },
  { id: "a-yang", name: "Zhilin Yang", affiliation: "Carnegie Mellon University", hIndex: 35 },
  { id: "a-liu-yinhan", name: "Yinhan Liu", affiliation: "FAIR", hIndex: 25 },
  { id: "a-brown", name: "Tom B. Brown", affiliation: "OpenAI", hIndex: 40 },
  { id: "a-dosovitskiy", name: "Alexey Dosovitskiy", affiliation: "Google Brain", hIndex: 55 },
  { id: "a-ramesh", name: "Aditya Ramesh", affiliation: "OpenAI", hIndex: 25 },
  { id: "a-jumper", name: "John Jumper", affiliation: "DeepMind", hIndex: 35 },
  { id: "a-ouyang", name: "Long Ouyang", affiliation: "OpenAI", hIndex: 15 },
  { id: "a-touvron", name: "Hugo Touvron", affiliation: "FAIR", hIndex: 20 },
  { id: "a-sanh", name: "Victor Sanh", affiliation: "Hugging Face", hIndex: 20 },
];

// Each paper: id, title, year, venue, topics[], authors[], abstract, citationCount (denormalised
// counter used for ranking — kept in sync by the seed script from actual :CITES edges), cites[]
const papers = [
  {
    id: "p-lstm-1997", title: "Long Short-Term Memory", year: 1997, venue: "v-neural-comp",
    topics: ["t-dl", "t-arch"], authors: ["a-hochreiter", "a-schmidhuber"],
    abstract: "Introduces a recurrent unit with gated memory cells that lets networks learn dependencies across long sequences without vanishing gradients.",
    cites: [],
  },
  {
    id: "p-word2vec-2013", title: "Efficient Estimation of Word Representations in Vector Space", year: 2013, venue: "v-arxiv",
    topics: ["t-nlp", "t-repr"], authors: ["a-mikolov"],
    abstract: "Proposes lightweight neural models that learn dense word vectors from large corpora, capturing analogical relationships between words.",
    cites: [],
  },
  {
    id: "p-alexnet-2012", title: "ImageNet Classification with Deep Convolutional Neural Networks", year: 2012, venue: "v-neurips",
    topics: ["t-cv", "t-dl"], authors: ["a-krizhevsky", "a-sutskever", "a-hinton"],
    abstract: "Trains a deep convolutional network on ImageNet with ReLUs and GPU acceleration, sharply reducing image classification error rates.",
    cites: [],
  },
  {
    id: "p-dropout-2014", title: "Dropout: A Simple Way to Prevent Neural Networks from Overfitting", year: 2014, venue: "v-jmlr",
    topics: ["t-opt", "t-dl"], authors: ["a-srivastava", "a-hinton", "a-krizhevsky", "a-sutskever", "a-salakhutdinov"],
    abstract: "Randomly drops units during training as a cheap approximation to averaging many networks, substantially reducing overfitting.",
    cites: [],
  },
  {
    id: "p-vgg-2014", title: "Very Deep Convolutional Networks for Large-Scale Image Recognition", year: 2014, venue: "v-iclr",
    topics: ["t-cv", "t-arch"], authors: ["a-simonyan", "a-zisserman"],
    abstract: "Shows that stacking many small 3x3 convolutions into very deep networks improves image recognition accuracy.",
    cites: ["p-alexnet-2012"],
  },
  {
    id: "p-gan-2014", title: "Generative Adversarial Networks", year: 2014, venue: "v-neurips",
    topics: ["t-gen", "t-dl"], authors: ["a-goodfellow", "a-bengio"],
    abstract: "Frames generative modeling as a two-player game between a generator and a discriminator trained simultaneously.",
    cites: [],
  },
  {
    id: "p-seq2seq-2014", title: "Sequence to Sequence Learning with Neural Networks", year: 2014, venue: "v-neurips",
    topics: ["t-nlp", "t-arch"], authors: ["a-sutskever", "a-vinyals", "a-le"],
    abstract: "Maps variable-length input sequences to variable-length outputs using paired encoder and decoder recurrent networks.",
    cites: ["p-lstm-1997"],
  },
  {
    id: "p-nmt-attn-2014", title: "Neural Machine Translation by Jointly Learning to Align and Translate", year: 2014, venue: "v-iclr",
    topics: ["t-nlp", "t-attn"], authors: ["a-bahdanau", "a-cho", "a-bengio"],
    abstract: "Adds a soft alignment mechanism to encoder-decoder translation models so the decoder can focus on relevant source words.",
    cites: ["p-seq2seq-2014", "p-lstm-1997"],
  },
  {
    id: "p-adam-2014", title: "Adam: A Method for Stochastic Optimization", year: 2014, venue: "v-iclr",
    topics: ["t-opt"], authors: ["a-kingma", "a-ba"],
    abstract: "Combines per-parameter adaptive learning rates with momentum, becoming a default optimizer for training deep networks.",
    cites: [],
  },
  {
    id: "p-batchnorm-2015", title: "Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift", year: 2015, venue: "v-icml",
    topics: ["t-opt", "t-dl"], authors: ["a-ioffe", "a-szegedy"],
    abstract: "Normalizes layer inputs within each mini-batch, allowing higher learning rates and faster, more stable training.",
    cites: ["p-alexnet-2012", "p-dropout-2014"],
  },
  {
    id: "p-resnet-2015", title: "Deep Residual Learning for Image Recognition", year: 2015, venue: "v-cvpr",
    topics: ["t-cv", "t-arch"], authors: ["a-he", "a-zisserman", "a-sun"],
    abstract: "Introduces residual shortcut connections that make it possible to train networks hundreds of layers deep.",
    cites: ["p-vgg-2014", "p-batchnorm-2015", "p-alexnet-2012"],
  },
  {
    id: "p-dqn-atari-2013", title: "Playing Atari with Deep Reinforcement Learning", year: 2013, venue: "v-arxiv",
    topics: ["t-rl", "t-dl"], authors: ["a-mnih", "a-kavukcuoglu", "a-silver"],
    abstract: "Combines convolutional networks with Q-learning and experience replay to learn Atari game play directly from pixels.",
    cites: ["p-alexnet-2012"],
  },
  {
    id: "p-dqn-nature-2015", title: "Human-level Control Through Deep Reinforcement Learning", year: 2015, venue: "v-nature",
    topics: ["t-rl"], authors: ["a-mnih", "a-kavukcuoglu", "a-silver", "a-hassabis"],
    abstract: "Extends the deep Q-network approach with a stabilised training procedure, reaching human-level performance across many Atari games.",
    cites: ["p-dqn-atari-2013"],
  },
  {
    id: "p-attention-2017", title: "Attention Is All You Need", year: 2017, venue: "v-neurips",
    topics: ["t-nlp", "t-attn", "t-arch"], authors: ["a-vaswani", "a-shazeer", "a-jones"],
    abstract: "Replaces recurrence entirely with self-attention layers, introducing the Transformer architecture for sequence modeling.",
    cites: ["p-nmt-attn-2014", "p-seq2seq-2014", "p-adam-2014", "p-dropout-2014", "p-batchnorm-2015"],
  },
  {
    id: "p-bert-2018", title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding", year: 2018, venue: "v-naacl",
    topics: ["t-nlp", "t-repr"], authors: ["a-devlin"],
    abstract: "Pre-trains a bidirectional Transformer with masked language modeling, then fine-tunes it for a wide range of NLP tasks.",
    cites: ["p-attention-2017", "p-word2vec-2013", "p-adam-2014"],
  },
  {
    id: "p-gpt-2018", title: "Improving Language Understanding by Generative Pre-Training", year: 2018, venue: "v-arxiv",
    topics: ["t-nlp", "t-repr"], authors: ["a-radford", "a-sutskever"],
    abstract: "Pre-trains a unidirectional Transformer as a language model, then fine-tunes it discriminatively across downstream tasks.",
    cites: ["p-attention-2017", "p-word2vec-2013"],
  },
  {
    id: "p-alphago-2016", title: "Mastering the Game of Go with Deep Neural Networks and Tree Search", year: 2016, venue: "v-nature",
    topics: ["t-rl", "t-arch"], authors: ["a-silver", "a-hassabis"],
    abstract: "Combines policy and value networks with Monte Carlo tree search to defeat top human players at Go.",
    cites: ["p-dqn-nature-2015", "p-resnet-2015"],
  },
  {
    id: "p-elmo-2018", title: "Deep Contextualized Word Representations", year: 2018, venue: "v-naacl",
    topics: ["t-nlp", "t-repr"], authors: ["a-peters"],
    abstract: "Derives word representations from an internal bidirectional LSTM language model, capturing context-dependent word meaning.",
    cites: ["p-word2vec-2013", "p-lstm-1997"],
  },
  {
    id: "p-gpt2-2019", title: "Language Models are Unsupervised Multitask Learners", year: 2019, venue: "v-arxiv",
    topics: ["t-nlp", "t-repr"], authors: ["a-radford"],
    abstract: "Shows that a sufficiently large Transformer language model trained on diverse web text performs many tasks with no task-specific fine-tuning.",
    cites: ["p-gpt-2018", "p-bert-2018", "p-attention-2017"],
  },
  {
    id: "p-transformer-xl-2019", title: "Transformer-XL: Attentive Language Models Beyond a Fixed-Length Context", year: 2019, venue: "v-acl",
    topics: ["t-nlp", "t-attn"], authors: ["a-dai", "a-yang"],
    abstract: "Adds segment-level recurrence and relative position encodings so Transformers can model dependencies beyond a fixed context window.",
    cites: ["p-attention-2017", "p-bert-2018"],
  },
  {
    id: "p-xlnet-2019", title: "XLNet: Generalized Autoregressive Pretraining for Language Understanding", year: 2019, venue: "v-neurips",
    topics: ["t-nlp", "t-repr"], authors: ["a-yang", "a-dai"],
    abstract: "Trains an autoregressive model over permuted token orders to capture bidirectional context without BERT's masking mismatch.",
    cites: ["p-bert-2018", "p-transformer-xl-2019", "p-gpt-2018"],
  },
  {
    id: "p-roberta-2019", title: "RoBERTa: A Robustly Optimized BERT Pretraining Approach", year: 2019, venue: "v-arxiv",
    topics: ["t-nlp", "t-repr"], authors: ["a-liu-yinhan"],
    abstract: "Retrains BERT with longer training, larger batches and more data, showing the original setup was significantly undertrained.",
    cites: ["p-bert-2018", "p-adam-2014"],
  },
  {
    id: "p-gpt3-2020", title: "Language Models are Few-Shot Learners", year: 2020, venue: "v-neurips",
    topics: ["t-nlp", "t-repr"], authors: ["a-brown", "a-radford", "a-sutskever"],
    abstract: "Scales a Transformer language model to 175 billion parameters, showing strong few-shot task performance from prompting alone.",
    cites: ["p-gpt2-2019", "p-bert-2018", "p-attention-2017", "p-transformer-xl-2019"],
  },
  {
    id: "p-vit-2020", title: "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale", year: 2020, venue: "v-iclr",
    topics: ["t-cv", "t-attn"], authors: ["a-dosovitskiy"],
    abstract: "Applies a Transformer directly to sequences of image patches, matching convolutional networks on large-scale image classification.",
    cites: ["p-attention-2017", "p-resnet-2015", "p-bert-2018"],
  },
  {
    id: "p-clip-2021", title: "Learning Transferable Visual Models From Natural Language Supervision", year: 2021, venue: "v-icml",
    topics: ["t-cv", "t-nlp", "t-repr"], authors: ["a-radford"],
    abstract: "Jointly trains image and text encoders on paired web data so images can be classified using natural-language prompts.",
    cites: ["p-vit-2020", "p-gpt2-2019", "p-resnet-2015"],
  },
  {
    id: "p-dalle-2021", title: "Zero-Shot Text-to-Image Generation", year: 2021, venue: "v-icml",
    topics: ["t-gen", "t-cv", "t-nlp"], authors: ["a-ramesh"],
    abstract: "Trains a Transformer to generate discrete image tokens from text, producing images directly from captions without task-specific supervision.",
    cites: ["p-clip-2021", "p-gpt2-2019", "p-gan-2014"],
  },
  {
    id: "p-alphafold-2021", title: "Highly Accurate Protein Structure Prediction with AlphaFold", year: 2021, venue: "v-nature",
    topics: ["t-dl", "t-arch"], authors: ["a-jumper", "a-hassabis"],
    abstract: "Uses an attention-based network over evolutionary and structural features to predict protein 3D structure with near-experimental accuracy.",
    cites: ["p-attention-2017", "p-resnet-2015"],
  },
  {
    id: "p-instructgpt-2022", title: "Training Language Models to Follow Instructions with Human Feedback", year: 2022, venue: "v-neurips",
    topics: ["t-nlp", "t-rl"], authors: ["a-ouyang"],
    abstract: "Fine-tunes a language model using reinforcement learning from human feedback to better follow user instructions.",
    cites: ["p-gpt3-2020", "p-dqn-nature-2015"],
  },
  {
    id: "p-llama-2023", title: "LLaMA: Open and Efficient Foundation Language Models", year: 2023, venue: "v-arxiv",
    topics: ["t-nlp", "t-repr"], authors: ["a-touvron"],
    abstract: "Trains a family of smaller, openly released language models on more tokens, matching much larger proprietary models on benchmarks.",
    cites: ["p-gpt3-2020", "p-roberta-2019", "p-attention-2017"],
  },
  {
    id: "p-distilbert-2019", title: "DistilBERT, a Distilled Version of BERT: Smaller, Faster, Cheaper and Lighter", year: 2019, venue: "v-arxiv",
    topics: ["t-compress", "t-nlp"], authors: ["a-sanh"],
    abstract: "Uses knowledge distillation during pre-training to compress BERT into a smaller model that keeps most of its performance.",
    cites: ["p-bert-2018", "p-dropout-2014"],
  },
];

module.exports = { venues, topics, authors, papers };
